export type Screen='home'|'bitcoin'|'dca'|'compare'|'lump'|'markets'|'temperature'|'alerts'|'opportunity';
export interface Asset {symbol:string;name:string;category:string}
export interface ChartPoint {date:string;portfolio_value:string;contributions:string}
export interface DcaResult {asset:string;asset_name:string;asset_type:string;requested_start_date:string;requested_end_date:string;effective_end_date:string;frequency:string;contribution:string;total_invested:string;total_units:string;average_purchase_price:string;final_value:string;profit:string;return_pct:string;purchase_count:number;chart:ChartPoint[]}
export interface LumpResult {asset:string;asset_name:string;effective_end_date:string;total_capital:string;dca:DcaResult;lump_sum:{total_invested:string;total_units:string;final_value:string;profit:string;return_pct:string};winner:string;value_difference:string}
export interface MarketTemperature {symbol:string;name:string;asset_class:string;as_of:string;current_price:number;opportunity_score:number;overheat_score:number;classification:string;trend:string;divergence:string;weekly_rsi:number|null;stochastic_rsi:number|null;sma_200w:number|null;distance_200w_percent:number|null;ath:number;drawdown_percent:number;sma_200d:number|null;sma_10m:number|null;momentum_12m:number|null;recovery_signal:boolean;history_status:string}
export interface Product {id:string;brand:string;category:string;family:string;model:string;release_date:string;release_year:number;launch_price_usd:string;image_url:string|null;source_url:string;active:boolean;display_order:number;custom:boolean}
export interface OpportunitySummary {total_spent:string;eligible_spent:string;current_value:string;gain:string;return_pct:string;investment_units:string;eligible_items:number;total_items:number}
export interface OpportunityResult {asset:Asset;current_price:string;current_price_date:string;summary:OpportunitySummary;items:{product:Product;quantity:number;cost:string;eligible:boolean;requested_date:string;price_date:string|null;asset_price:string|null;units:string;current_value:string;gain:string|null;reason:string|null}[]}
export interface OpportunityRanking {asset:Asset;current_price:string;current_price_date:string;summary:OpportunitySummary}
export interface BitcoinResearchState {as_of:string;quantile:{as_of:string;price:number;percentile:number;bands:{quantile:number;price:number}[];method:string}|null;mvrv:{as_of:string;price:number|null;value:number;percentile:number;history_observations:number;age_days:number;freshness:string;source:string}|null;top_stage2:{active:boolean;warning_date:string|null;confirmation_date:string|null;warning_age_days:number|null;current_any2_streak_days:number;primitive_count:number;primitives:{below_50d_sma:boolean;momentum_30d_negative:boolean;drawdown_10pct:boolean;overheat_rollover_20:boolean};rule:string;reason:string}|null;quantile_error?:string;mvrv_error?:string;top_stage2_error?:string}
export interface AlertRule {id:number;scope_type:string;scope_value:string|null;metric:string;operator:string;numeric_value:number|null;text_value:string|null;enabled:boolean;notify_on_enter:boolean;notify_on_exit:boolean;cooldown_minutes:number;delivery_channel:string}

export interface CustomPurchase {id:string;name:string;purchase_date:string;price_usd:string;quantity:number;category:string;custom:true}
